# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logical_clock.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logical_clock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13logical_clock.proto\x12\x0clogicalclock\"M\n\x0c\x43lockMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x15\n\rlogical_clock\x18\x02 \x01(\x03\x12\x13\n\x0bsystem_time\x18\x03 \x01(\x03\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\x0c\x43lockService\x12<\n\x0bSendMessage\x12\x1a.logicalclock.ClockMessage\x1a\x11.logicalclock.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logical_clock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKMESSAGE']._serialized_start=37
  _globals['_CLOCKMESSAGE']._serialized_end=114
  _globals['_ACK']._serialized_start=116
  _globals['_ACK']._serialized_end=138
  _globals['_CLOCKSERVICE']._serialized_start=140
  _globals['_CLOCKSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
